/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, MeshDistortMaterial } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Rocket1.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Wings.geometry}
          material={materials.Wings}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh geometry={nodes.Smoke.geometry} rotation={[Math.PI / 2, 0, 0]}>
          <MeshDistortMaterial
            attach="material"
            color={"#d1c8b9"}
            radius={1}
            distort={0.5}
            speed={1.5}
          />
        </mesh>
        <mesh
          geometry={nodes.Body.geometry}
          material={materials.Body}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Rocket1.glb");
